document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=gb2312\" \/>");
document.writeln("<link href=\"images\/images\/style.css\" rel=\"stylesheet\" type=\"text\/css\" media=\"all\">");
document.writeln("<div id=\"css8_header\">");
document.writeln("	<div id=\"css8_header1\">");
document.writeln("				<H1><A href=\"http:\/\/www.css8.cn\/\">css8.cn样吧,标准网页设计<\/A><\/H1>");
document.writeln("				<UL>");
document.writeln("						<LI class=\"home\"><A class=menu2 href=\"l_Object.html\" onFocus=\"this.blur()\"><span><span><span>Object<\/span><\/span><\/span><\/A><\/LI>");
document.writeln("						<LI><A class=menu3 href=\"l_Arguments.html\" onFocus=\"this.blur()\"><span><span><span>Arguments<\/span><\/span><\/span><\/A><\/LI>");
document.writeln("						<LI><A class=menu4 href=\"l_Array.htm\" onFocus=\"this.blur()\"><span><span><span>Array<\/span><\/span><\/span><\/A><\/LI>");
document.writeln("						<LI><A class=menu5 href=\"l_Boolean.html\" onFocus=\"this.blur()\"><span><span><span>Boolean<\/span><\/span><\/span><\/A><\/LI>");
document.writeln("						<LI><A class=menu6 href=\"l_Date.html\" onFocus=\"this.blur()\"><span><span><span>Date<\/span><\/span><\/span><\/A><\/LI>");
document.writeln("						<LI><A class=menu7 href=\"l_Error.html\" onFocus=\"this.blur()\"><span><span><span>Error<\/span><\/span><\/span><\/A><\/LI>			");
document.writeln("						<LI><A class=menu8 href=\"l_Function.html\" onFocus=\"this.blur()\"><span><span><span>Function<\/span><\/span><\/span><\/A><\/LI>			");
document.writeln("						<LI><A class=menu9 href=\"l_math.html\" onFocus=\"this.blur()\"><span><span><span>Math<\/span><\/span><\/span><\/A><\/LI>	");
document.writeln("						<LI><A class=menu10 href=\"l_Number.html\" onFocus=\"this.blur()\"><span><span><span>Number<\/span><\/span><\/span><\/A><\/LI>		");
document.writeln("						<LI><A class=menu11 href=\"l_RegExp.html\" onFocus=\"this.blur()\"><span><span><span>RegExp<\/span><\/span><\/span><\/A><\/LI>");
document.writeln("						<LI><A class=menu12 href=\"l_String.html\" onFocus=\"this.blur()\"><span><span><span>String<\/span><\/span><\/span><\/A><\/LI>");
document.writeln("				<\/UL>");
document.writeln("				<div id=\"css8_header2\"><div><div>");
document.writeln("					<dl>");
document.writeln("						<dt>站点导航<\/dt>		");
document.writeln("						<dd>");
document.writeln("<img src=\"images\/icon3.gif\" \/> <a href=\"l_Global.html\" >Global<\/a>						");
document.writeln("						<\/dd>");
document.writeln("						<dd>");
document.writeln("<img src=\"images\/icon3.gif\" \/> <a href=\"l_Code.html\" >Code<\/a>						");
document.writeln("						<\/dd>                        ");
document.writeln("						<dd>");
document.writeln("<img src=\"images\/icon3.gif\" \/> <a href=\"l_Eval.html\">Eval<\/a>						");
document.writeln("						<\/dd>");
document.writeln("						<dd>");
document.writeln("<img src=\"images\/icon3.gif\" \/> <a href=\"l_Variant.html\" >Variant<\/a>						");
document.writeln("						<\/dd>													");
document.writeln("");
document.writeln("					<\/dl>");
document.writeln("				<\/div><\/div><\/div>	");
document.writeln("");
document.writeln("<div id=\"css_first\">");
document.writeln("	<a href=\"main.html\" >JavaScript核心参考索引<\/a>  ");
document.writeln("	<a href=\"ch23-3-fm2xml.html\" >JavaScript核心参考说明<\/a> ");
document.writeln("<\/div>");
document.writeln("");
document.writeln("	<\/div>");
document.writeln("<\/div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");